import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const CONTRACT="1.1"; type Obj=Record<string,unknown>;
const cors={"Access-Control-Allow-Origin":"https://beat-vision-f8nn.vercel.app","Access-Control-Allow-Headers":"authorization, apikey, x-client-info, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const env=(n:string)=>String(Deno.env.get(n)||"").trim(); const text=(v:unknown)=>String(v??"").trim(); const num=(v:unknown,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
function tokenOf(r:Request){const m=(r.headers.get("Authorization")||"").match(/^Bearer\s+(.+)$/i);if(!m)throw new Error("Authentication required.");return m[1]}
const base=()=>env("SUPABASE_URL").replace(/\/$/,""); const key=()=>env("SUPABASE_ANON_KEY")||env("SUPABASE_PUBLISHABLE_KEY");
async function auth(r:Request){const token=tokenOf(r);const z=await fetch(base()+"/auth/v1/user",{headers:{apikey:key(),Authorization:`Bearer ${token}`}});if(!z.ok)throw new Error("Invalid or expired authentication session.");const u=await z.json();if(!u?.id)throw new Error("Authenticated user could not be established.");return{token,uid:String(u.id)}}
async function db(token:string,path:string,init:RequestInit={}):Promise<any>{const z=await fetch(base()+"/rest/v1/"+path,{...init,headers:{apikey:key(),Authorization:`Bearer ${token}`,Accept:"application/json","Content-Type":"application/json",...(init.headers||{})}});const raw=await z.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!z.ok)throw new Error(`Database request failed (${z.status}): ${String(d?.message||d?.error||raw).slice(0,700)}`);return d}
async function arena(prompt:string,token:string,timing:{duration:number;start:number;end:number}){const groqKey=env("GROQ_API_KEY");if(!groqKey)throw new Error("BeatVision language provider is unavailable: GROQ_API_KEY is not configured.");const z=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+groqKey},body:JSON.stringify({model:"openai/gpt-oss-20b",temperature:0.25,max_completion_tokens:4000,response_format:{type:"json_object"},messages:[{role:"system",content:"You are BeatVision's storyboard director. Return ONLY valid JSON. Do not invent lyrics. Respect the supplied absolute time window exactly. Generate visual beats with enough specificity for downstream image generation while preserving the supplied World context."},{role:"user",content:prompt}]}),signal:AbortSignal.timeout(100000)});const raw=await z.text();let d:any;try{d=raw?JSON.parse(raw):null}catch{d=null}if(!z.ok)throw new Error("Groq storyboard provider returned HTTP "+z.status+": "+String(d?.error?.message||raw).slice(0,900));const content=d?.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("Groq storyboard provider returned no content.");try{return JSON.parse(content)}catch{throw new Error("Groq storyboard provider returned invalid JSON.")}}
function parseClock(v:string){const p=v.trim().split(":").map(Number);if(p.some(n=>!Number.isFinite(n)))return NaN;return p.length===1?p[0]:p[0]*60+p[1]}
function fmt(s:number){return `${Math.floor(s/60)}:${String(Math.round(s%60)).padStart(2,"0")}`}
function extract(raw:any){const a=Array.isArray(raw?.visual_beats)?raw.visual_beats:Array.isArray(raw?.scenes)?raw.scenes:Array.isArray(raw)?raw:[];if(!a.length)throw new Error("Storyboard provider returned no visual beats.");return a}
Deno.serve(async r=>{let runKey="";let projectIdForError="";let ownerIdForError="";let token="";if(r.method==="OPTIONS")return new Response("ok",{headers:cors});try{if(r.method!=="POST")return json({error:"POST required"},405);const authResult=await auth(r);token=authResult.token;const uid=authResult.uid;ownerIdForError=uid;const body:any=await r.json();const pid=text(body.projectId||body.project_id);projectIdForError=pid;if(!pid)throw new Error("projectId is required.");const rows=await db(token,`projects?select=*&id=eq.${encodeURIComponent(pid)}&owner_id=eq.${encodeURIComponent(uid)}&limit=1`);if(!rows?.length)throw new Error("Project access denied.");const p=rows[0];const duration=num(p.song_duration);if(!(duration>0))throw new Error("Song duration is missing. Re-upload the song or set its duration before generating the storyboard.");const chunkSeconds=45;const index=Math.max(0,Math.floor(num(body.chunk,0)));const start=Math.min(duration,index*chunkSeconds);const end=Math.min(duration,start+chunkSeconds);if(start>=duration)return json({success:true,done:true,chunk:index,scene_count:0});
const generationId=text(body.generationId);if(!/^[A-Za-z0-9_-]{16,100}$/.test(generationId))throw Object.assign(new Error("generationId must be a stable client-generated identifier."),{status:400});runKey=`storyboard:${generationId}:${index}`;const existingRuns=await db(token,`generation_runs?select=id,status,output_json&project_id=eq.${encodeURIComponent(pid)}&owner_id=eq.${encodeURIComponent(uid)}&request_key=eq.${encodeURIComponent(runKey)}&limit=1`);const existingRun=existingRuns?.[0];if(existingRun?.status==="completed"&&existingRun.output_json?.response)return json(existingRun.output_json.response);if(existingRun?.status==="running")throw Object.assign(new Error(`Storyboard chunk ${index} is already running.`),{status:409});await db(token,"generation_runs",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({project_id:pid,owner_id:uid,action:"storyboard_chunk",request_key:runKey,input_hash:runKey,status:"running",provider:"beatvision-storyboard",model:"chunk-controller",started_at:new Date().toISOString()})});if(index===0){await db(token,`storyboard_scenes?project_id=eq.${encodeURIComponent(pid)}`,{method:"DELETE"});}
const wr=(await db(token,`visual_world_reports?select=*&project_id=eq.${encodeURIComponent(pid)}&order=created_at.desc&limit=1`))[0]||{};const prompt=`Create ONLY the storyboard beats for the song interval ${start.toFixed(2)} to ${end.toFixed(2)} seconds. Full song duration is ${duration.toFixed(2)} seconds. Song title: "${p.title}". Style: ${p.selected_style||"Cinematic"}. Lyrics:\n${String(p.lyrics||"").slice(0,30000)}\nWorld context: ${JSON.stringify(wr)}\nReturn ONLY JSON object {"visual_beats":[...]}. Every beat MUST have absolute numeric startTime/endTime within ${start.toFixed(2)} and ${end.toFixed(2)}, beatId, sectionId, lyricRange, lyricMeaning, narrativePurpose, emotionalState, emotionalIntensity, characterState, environment, action, visualConcept, symbolicElements, cameraIntent, transitionIntent, reusePolicy. Start exactly at ${start.toFixed(2)} and end exactly at ${end.toFixed(2)}. Use enough beats to reflect lyric changes and instrumental moments, but keep the response concise. Never invent lyrics and mark instrumental intervals as non-lyrical. No markdown.`;
const beats=extract(await arena(prompt,token,{duration,start,end}));
// Fetch the current max scene_number BEFORE writing this chunk so we have
// a stable base. The actual offset used for numbering is fetched again AFTER
// writing to be DB-authoritative, eliminating the race condition where a
// concurrent chunk reads a stale offset.
const normalized:any[]=[];for(let i=0;i<beats.length;i++){const b=beats[i]||{};let s=num(b.startTime??b.start_time,NaN),e=num(b.endTime??b.end_time,NaN);if(!Number.isFinite(s)||!Number.isFinite(e))throw new Error(`Storyboard beat ${i+1} has invalid timing.`);s=Math.max(start,Math.min(end,s));e=Math.max(s,Math.min(end,e));if(e<=s)continue;normalized.push({startTime:s,endTime:e,beatId:text(b.beatId??b.beat_id)||`chunk-${index}-beat-${i+1}`,scene_title:text(b.scene_title??b.narrativePurpose??b.visualConcept)||`Scene ${index*1000+i+1}`,timestamp_range:`${fmt(s)} - ${fmt(e)}`,visual_description:text(b.visual_description??b.description??b.visualConcept),camera_direction:text(b.camera_direction??b.cameraIntent),mood:text(b.mood??b.emotionalState),location:text(b.location??b.environment),lyric_moment:text(b.lyric_moment??b.lyricMeaning),transition_style:text(b.transition_style??b.transitionIntent)});}
if(!normalized.length)throw new Error("Storyboard chunk produced no usable scenes.");
// Fetch DB-authoritative max scene_number immediately before inserting this chunk.
// This is the race-safe approach: the offset is read as late as possible so any
// previously committed chunk's scenes are already visible.
let insertSucceeded=false;
for(let attempt=0;attempt<3 && !insertSucceeded;attempt++){
  const offsetRows=index===0?[]:await db(token,"storyboard_scenes?select=scene_number&project_id=eq."+encodeURIComponent(pid)+"&order=scene_number.desc&limit=1");
  const sceneOffset=index===0?0:Number(offsetRows?.[0]?.scene_number||0);
  const rows=normalized.map((b:any,i:number)=>({
    project_id:pid,owner_id:uid,scene_number:sceneOffset+i+1,
    timestamp_range:b.timestamp_range,scene_title:b.scene_title,
    visual_description:b.visual_description,camera_direction:b.camera_direction,
    mood:b.mood,location:b.location,lyric_moment:b.lyric_moment,
    transition_style:b.transition_style,approved:false,needs_review:false,
    updated_after_approval:false
  }));
  try{
    await db(token,"storyboard_scenes",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify(rows)});
    insertSucceeded=true;
  }catch(error){
    const message=String(error instanceof Error?error.message:error);
    if(attempt===2 || !/409|duplicate|unique/i.test(message))throw error;
  }
}
if(!insertSucceeded)throw new Error("Storyboard scene insert could not obtain a unique scene range after retries.");
const next=end<duration-0.01?index+1:null;const response={success:true,done:next===null,chunk:index,next,scene_count:normalized.length,start,end,duration,generationId};await db(token,`generation_runs?project_id=eq.${encodeURIComponent(pid)}&owner_id=eq.${encodeURIComponent(uid)}&request_key=eq.${encodeURIComponent(runKey)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"completed",output_json:{response},completed_at:new Date().toISOString()})});
if(next===null)await db(token,`projects?id=eq.${encodeURIComponent(pid)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"Storyboard Ready",storyboard_approved:false,updated_at:new Date().toISOString()})});
return json(response);}catch(e){if(runKey){try{await db(token,`generation_runs?project_id=eq.${encodeURIComponent(projectIdForError)}&owner_id=eq.${encodeURIComponent(ownerIdForError)}&request_key=eq.${encodeURIComponent(runKey)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"failed",error_code:"STORYBOARD_CHUNK_FAILED",error_message:String(e instanceof Error?e.message:e).slice(0,1600)})})}catch{}}const m=e instanceof Error?e.message:String(e);return json({success:false,error:m},/Authentication|expired|authenticated/.test(m)?401:/access denied/.test(m)?403:Number((e as {status?:number})?.status)||500)}});